services:
  gnu-hurd-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: gnu-hurd-docker:latest
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - ./images/debian-hurd-amd64.qcow2:/opt/hurd-image/debian-hurd-amd64.qcow2:rw
      - ./share:/share:rw
