name: 'Workflow Summary Generator'
description: 'Generate comprehensive workflow summary for GitHub Actions'
author: 'GNU/Hurd Docker Team'

inputs:
  workflow-name:
    description: 'Name of the workflow'
    required: true
  status:
    description: 'Workflow status (use ${{ job.status }})'
    required: true
  checks-performed:
    description: 'Markdown list of checks performed'
    required: true
  additional-info:
    description: 'Additional markdown content'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Generate Summary
      shell: bash
      run: |
        cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        ## ${{ inputs.status == 'success' && '✅' || '❌' }} ${{ inputs.workflow-name }} - Summary
        
        **Workflow:** ${{ inputs.workflow-name }}
        **Status:** ${{ inputs.status }}
        **Run ID:** ${{ github.run_id }}
        **Triggered by:** ${{ github.event_name }}
        
        ### Checks Performed
        ${{ inputs.checks-performed }}
        
        ${{ inputs.additional-info }}
        
        ---
        *Generated by workflow-summary composite action*
        EOF

branding:
  icon: 'activity'
  color: 'purple'
