#!/bin/bash
# GNU/Hurd User Account Configuration Script
# Configures root and agents accounts with proper permissions and sudo access
# Version: 1.0
# Date: 2025-11-05

set -euo pipefail

echo "======================================================================"
echo "  GNU/Hurd Docker - User Account Configuration"
echo "======================================================================"
echo ""
echo "This script will configure:"
echo "  - root account with password 'root'"
echo "  - agents account with password 'agents'"
echo "  - sudo access for agents with NOPASSWD"
echo "  - SSH access for both accounts"
echo "  - Proper home directory permissions"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root"
    exit 1
fi

echo "[1/6] Setting root password..."
echo "root:root" | chpasswd
echo "  ✓ Root password set to 'root'"

echo ""
echo "[2/6] Creating agents user..."
if id "agents" &>/dev/null; then
    echo "  ⚠ User 'agents' already exists, skipping creation"
else
    useradd -m -s /bin/bash agents
    echo "  ✓ User 'agents' created with home directory /home/agents"
fi

echo ""
echo "[3/6] Setting agents password..."
echo "agents:agents" | chpasswd
echo "  ✓ Agents password set to 'agents'"

echo ""
echo "[4/6] Configuring sudo access..."
# Install sudo if not present
if ! command -v sudo &> /dev/null; then
    echo "  → Installing sudo package..."
    apt-get update -qq
    apt-get install -y sudo
fi

# Add agents to sudo group (if group exists)
if getent group sudo > /dev/null 2>&1; then
    usermod -a -G sudo agents
    echo "  ✓ Added agents to sudo group"
else
    echo "  ⚠ sudo group not found, creating sudoers.d entry instead"
fi

# Create sudoers configuration for agents
mkdir -p /etc/sudoers.d
cat > /etc/sudoers.d/agents << 'EOF'
# Allow agents user to run all commands without password
# Generated by configure-users.sh
agents ALL=(ALL:ALL) NOPASSWD:ALL
EOF

chmod 0440 /etc/sudoers.d/agents
echo "  ✓ Sudo configuration created at /etc/sudoers.d/agents"

# Validate sudoers syntax
if command -v visudo &> /dev/null; then
    visudo -c -f /etc/sudoers.d/agents || {
        echo "ERROR: Sudoers syntax validation failed"
        rm -f /etc/sudoers.d/agents
        exit 1
    }
    echo "  ✓ Sudoers syntax validated"
fi

echo ""
echo "[5/6] Setting up SSH access..."
# Create .ssh directories for both users
mkdir -p /root/.ssh /home/agents/.ssh
chmod 700 /root/.ssh /home/agents/.ssh
chown root:root /root/.ssh
chown agents:agents /home/agents/.ssh

# Create authorized_keys files (empty for now)
touch /root/.ssh/authorized_keys /home/agents/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys /home/agents/.ssh/authorized_keys
chown root:root /root/.ssh/authorized_keys
chown agents:agents /home/agents/.ssh/authorized_keys

echo "  ✓ SSH directories created with proper permissions"
echo "  → Add SSH public keys to:"
echo "      /root/.ssh/authorized_keys"
echo "      /home/agents/.ssh/authorized_keys"

echo ""
echo "[6/6] Verifying configuration..."
echo "  → Verifying user accounts..."
id root > /dev/null && echo "    ✓ root account verified"
id agents > /dev/null && echo "    ✓ agents account verified"

echo "  → Verifying sudo access..."
if sudo -u agents sudo -n true 2>/dev/null; then
    echo "    ✓ agents can use sudo without password"
else
    echo "    ⚠ sudo test failed (may need reboot)"
fi

echo "  → Verifying home directories..."
[ -d /root ] && echo "    ✓ /root exists"
[ -d /home/agents ] && echo "    ✓ /home/agents exists"

echo ""
echo "======================================================================"
echo "  User Configuration Complete!"
echo "======================================================================"
echo ""
echo "Account Summary:"
echo "  root"
echo "    Password: root"
echo "    SSH: ssh root@localhost -p 2222"
echo ""
echo "  agents"
echo "    Password: agents"
echo "    Sudo: NOPASSWD access enabled"
echo "    SSH: ssh agents@localhost -p 2222"
echo ""
echo "Security Notes:"
echo "  ⚠ These are default development passwords"
echo "  ⚠ Change passwords for production use"
echo "  ⚠ Add SSH keys for key-based authentication"
echo ""
echo "Next steps:"
echo "  1. Login as agents: su - agents"
echo "  2. Test sudo: sudo whoami (should output 'root')"
echo "  3. Run configure-shell.sh to customize environment"
echo ""
