#!/bin/bash
# GNU/Hurd Shell Environment Configuration Script
# Configures bash environment with Mach-specific paths and aliases
# Version: 1.0
# Date: 2025-11-05

set -euo pipefail

echo "======================================================================"
echo "  GNU/Hurd Docker - Shell Environment Configuration"
echo "======================================================================"
echo ""
echo "This script will configure bash environment for:"
echo "  - Mach development paths (headers, libraries, tools)"
echo "  - Colorized prompt with Git branch display"
echo "  - Useful aliases for development"
echo "  - Environment variables for build systems"
echo ""

# Determine target user (run as target user, not root)
TARGET_USER="${SUDO_USER:-$USER}"
if [ "$TARGET_USER" = "root" ] && [ "$EUID" -eq 0 ]; then
    echo "Configuring for: root"
    TARGET_HOME="/root"
else
    echo "Configuring for: $TARGET_USER"
    TARGET_HOME=$(eval echo ~$TARGET_USER)
fi

BASHRC="$TARGET_HOME/.bashrc"
echo "  Target .bashrc: $BASHRC"
echo ""

# Backup existing .bashrc if it exists
if [ -f "$BASHRC" ]; then
    BACKUP="$BASHRC.backup.$(date +%Y%m%d_%H%M%S)"
    cp "$BASHRC" "$BACKUP"
    echo "[Backup] Existing .bashrc saved to: $BACKUP"
fi

echo ""
echo "[1/4] Adding Mach development environment variables..."

# Append configuration to .bashrc
cat >> "$BASHRC" << 'EOF'

# ==============================================================================
# GNU/Hurd Development Environment
# Generated by configure-shell.sh
# ==============================================================================

# Mach development paths
export MACH_ROOT=/usr/src/gnumach
export PATH=$PATH:/usr/lib/mig/bin
export MANPATH=$MANPATH:/usr/share/man/mach
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/x86_64-gnu/pkgconfig

# Build configuration
export CC=gcc
export CXX=g++
export MAKE=make

# Enable ccache if installed
if command -v ccache >/dev/null 2>&1; then
    export CC="ccache gcc"
    export CXX="ccache g++"
fi

EOF

echo "  ✓ Environment variables added"

echo ""
echo "[2/4] Configuring colorized prompt..."

cat >> "$BASHRC" << 'EOF'
# Colorized prompt with Git branch support
# Format: [user@host:dir (git-branch)] $
parse_git_branch() {
    git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

if [ -n "$PS1" ]; then
    PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;33m\]$(parse_git_branch)\[\033[00m\]\$ '
fi

EOF

echo "  ✓ Colorized prompt configured"

echo ""
echo "[3/4] Adding development aliases..."

cat >> "$BASHRC" << 'EOF'
# Development aliases
alias ll='ls -lahF --color=auto'
alias la='ls -AF --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Mach-specific aliases
alias mig-version='mig --version 2>&1 | head -1'
alias mach-info='uname -a && cat /proc/cpuinfo | grep -E "model name|cpu MHz|cache size" | head -3'
alias mach-memory='free -h && cat /proc/meminfo | grep -E "MemTotal|MemFree|MemAvailable"'

# Build system shortcuts
alias cmake-debug='cmake -DCMAKE_BUILD_TYPE=Debug'
alias cmake-release='cmake -DCMAKE_BUILD_TYPE=Release'
alias configure-debug='./configure CFLAGS="-g -O0" CXXFLAGS="-g -O0"'
alias configure-release='./configure CFLAGS="-O2 -DNDEBUG" CXXFLAGS="-O2 -DNDEBUG"'

# Git shortcuts
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'
alias gd='git diff'

# Safety aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# System monitoring
alias ports='netstat -tulanp'
alias meminfo='free -h && cat /proc/meminfo | head -10'
alias cpuinfo='cat /proc/cpuinfo'
alias diskinfo='df -h'

EOF

echo "  ✓ Development aliases added"

echo ""
echo "[4/4] Adding Mach-specific helper functions..."

cat >> "$BASHRC" << 'EOF'
# Mach development helper functions

# Quick recompile and test
mach-rebuild() {
    if [ -f Makefile ]; then
        make clean && make && make check
    elif [ -f meson.build ]; then
        meson compile -C builddir && meson test -C builddir
    elif [ -f CMakeLists.txt ]; then
        cmake --build build && ctest --test-dir build
    else
        echo "No recognized build system found (Makefile, meson.build, or CMakeLists.txt)"
        return 1
    fi
}

# Show Mach system information
mach-sysinfo() {
    echo "=== GNU Mach System Information ==="
    echo ""
    echo "Kernel:"
    uname -a
    echo ""
    echo "CPU:"
    cat /proc/cpuinfo | grep -E "model name|cpu MHz" | head -2
    echo ""
    echo "Memory:"
    free -h | grep -E "Mem:|Swap:"
    echo ""
    echo "Disks:"
    df -h | grep -E "Filesystem|/dev/"
    echo ""
    echo "Packages:"
    dpkg -l | grep -E "gnumach|hurd|mig" | awk '{print $2, $3}'
}

# Search Mach documentation
mach-doc() {
    if [ -z "$1" ]; then
        echo "Usage: mach-doc <search-term>"
        return 1
    fi
    man -k "$1" | grep -i "mach\|hurd\|mig"
}

EOF

echo "  ✓ Helper functions added"

# Set ownership if configuring for non-root user
if [ "$EUID" -eq 0 ] && [ "$TARGET_USER" != "root" ]; then
    chown $TARGET_USER:$TARGET_USER "$BASHRC"
    echo "  ✓ Set ownership to $TARGET_USER"
fi

echo ""
echo "======================================================================"
echo "  Shell Configuration Complete!"
echo "======================================================================"
echo ""
echo "Configuration applied to: $BASHRC"
echo ""
echo "Reload configuration:"
echo "  source ~/.bashrc"
echo ""
echo "New features:"
echo "  Environment:"
echo "    - MACH_ROOT=/usr/src/gnumach"
echo "    - MIG tools in PATH"
echo "    - Man pages configured"
echo ""
echo "  Prompt:"
echo "    - Colorized with Git branch support"
echo "    - Format: [user@host:dir (branch)] $"
echo ""
echo "  Aliases:"
echo "    ll         - Detailed file listing"
echo "    mig-version - Show MIG version"
echo "    mach-info  - System information"
echo "    gs, ga, gc - Git shortcuts"
echo ""
echo "  Functions:"
echo "    mach-rebuild  - Clean, build, and test"
echo "    mach-sysinfo  - Comprehensive system info"
echo "    mach-doc <term> - Search Mach documentation"
echo ""
echo "Test your configuration:"
echo "  source ~/.bashrc"
echo "  mach-sysinfo"
echo "  mig-version"
echo ""
